In [2]:
import numpy as np

In [16]:
a = np.array([[3, 1, 4], [2, 6, 5]])

print(a)

c = a.copy()

c[1][1] = 10

a

[[3 1 4]
 [2 6 5]]


array([[3, 1, 4],
       [2, 6, 5]])

In [17]:
arr = np.array([[4,12,1],[7,5,3],[2,8,9]])

print(arr.shape)

print(arr < 5)
print(arr[arr<5])
print((arr[arr<5]).shape)

(3, 3)
[[ True False  True]
 [False False  True]
 [ True False False]]
[4 1 3 2]
(4,)


In [18]:
x = np.arange(1,25).reshape(2,12)

print(x)

np.hsplit(x,3)

np.hsplit(x, (2, 5))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [19]:
data = np.array([[1, 2], [3, 4], [5, 6]])
#ones_row = np.array([[1, 1]])
ones_col = np.ones(3).reshape(3,1)
data + ones_col

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [20]:
np.random.random(3)

array([0.81215409, 0.77946805, 0.59368694])

In [21]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_cols = np.unique(a_2d, axis=1)
print(unique_cols)

[11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [22]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

x = x.ravel()

x[1] = 92

x

array([ 1, 92,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
a = np.array([11, 11, 12, 13, 14])
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

for i in a:
    print(i)

print()

for i in x:
    print(i)

11
11
12
13
14

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [13]:
a = np.arange(5)
a[[1,2,3]] = [6,6,6]
a

array([0, 6, 6, 6, 4])